/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "domstubs.idl"

interface nsIDOMCRMFObject;
interface nsIDOMWindow;

[scriptable, uuid(0011b656-a303-469b-a358-185901cd30be)]
interface nsIDOMCrypto : nsISupports
{
  [noscript, notxpcom]void   init(in nsIDOMWindow window);
  readonly attribute DOMString        version;
  attribute boolean         enableSmartCardEvents;

  nsIDOMCRMFObject          generateCRMFRequest(/* ... */);
  DOMString                 importUserCertificates(in DOMString nickname,
                                                   in DOMString cmmfResponse,
                                                   in boolean doForcedBackup);
  DOMString                 popChallengeResponse(in DOMString challenge);
  DOMString                 random(in long numBytes);
  DOMString                 signText(in DOMString stringToSign,
                                     in DOMString caOption /* ... */);
  void                      logout();
  void                      disableRightClick();

  [implicit_jscontext] jsval getRandomValues(in jsval aData);
};
